language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - npm install -g npm
  - npm install bigpipe/pagelet
  - npm install bigpipe/pipe.js
  - cd node_modules/pipe.js && npm install browserify && npm run compile && cd ../../
notifications:
  irc:
    channels: "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
